// RootLayout.tsx
import type { Metadata } from "next";

import { auth } from "@/auth";

import localFont from "next/font/local";
import "./globals.css";

import { ThemeProvider } from "next-themes";

import { Toaster } from "sonner";

import AuthProvider from "@/provider/AuthProvider";
import { CartProvider } from "@/context/CartContext";
import NextTopLoader from "nextjs-toploader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const vazir = localFont({
  src: "./fonts/Vazir-FD.woff2", // Use FD version
  variable: "--font-vazir",
});

export const metadata: Metadata = {
  title: "My Chat Window",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  // Log to confirm server has it (which we know it does)
  if (session) {
    console.log("✅ RootLayout: Session loaded for", session.user?.email);
  } else {
    console.log("❌ RootLayout: No session found");
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${vazir.variable} bg-[#252525] text-black antialiased dark:text-white`}
      >
        {/* <NavigationLoader /> TODO: add this */}
        <ThemeProvider
          attribute="class" // Uses 'dark' class for dark mode
          defaultTheme="system" // Defaults to system preference, can be 'light' or 'dark'
          enableSystem // Enables system theme detection
          disableTransitionOnChange // Optional: Disables flash on theme change
        >
          <NextTopLoader
            color="#e8ca89"
            initialPosition={0.08}
            crawlSpeed={200}
            height={3}
            crawl={true}
            showSpinner={false}
            easing="ease"
            speed={200}
            shadow="0 0 10px #e8ca89,0 0 5px #e8ca89"
          />
          {/* <ThemeProvider defaultTheme="system" storageKey="app-theme"> */}
          <AuthProvider session={session}>
            <CartProvider>{children}</CartProvider>
          </AuthProvider>
          <Toaster dir="rtl" />
        </ThemeProvider>
      </body>
    </html>
  );
}
